name: Release

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  # actions: write

env:
  FORCE_COLOR: 3

jobs:
  release:
    runs-on: ubuntu-22.04

    if: github.ref == 'refs/heads/saga'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Get current tag
        run: |
          CURRENT_TAG=`git describe --tags --abbrev=0`
          echo "CURRENT_TAG=${CURRENT_TAG}" >> $GITHUB_ENV
          echo "CURRENT TAG > ${CURRENT_TAG}"

      # - name: View context attributes
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       console.log(context)
      #       console.log(context.repo)

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Trigger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run deploy.yaml
